version: 2
jobs:
  build-v4.8.1:
    docker:
      - image: docker:stable
        environment:
          DOCKER_DRIVER: overlay2
          MAJOR_VERSION: '4'
          MINOR_VERSION: '4.8'
          FULL_VERSION: '4.8.1'
          SHA256: 472c555677016da3a41ef052c5b9d82a78cd04c6db84a2067064d9475c6f9830
          CI_REGISTRY_IMAGE: 'containerinfra/keycloak-gatekeeper'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          docker pull $CI_REGISTRY_IMAGE:$FULL_VERSION || true

          docker build --cache-from $CI_REGISTRY_IMAGE:$FULL_VERSION --build-arg KEYCLOAK_GATEKEEPER_VERSION=${FULL_VERSION}.Final --build-arg=KEYCLOAK_GATEKEEPER_SHA256=$SHA256 -t $CI_REGISTRY_IMAGE:$FULL_VERSION --label org.opencontainers.image.revision=$CIRCLE_SHA1 .
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:$MINOR_VERSION
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:$MAJOR_VERSION
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:latest
          docker push $CI_REGISTRY_IMAGE:$FULL_VERSION
          docker push $CI_REGISTRY_IMAGE:$MINOR_VERSION
          docker push $CI_REGISTRY_IMAGE:$MAJOR_VERSION
          docker push $CI_REGISTRY_IMAGE:latest

  build-v4.8.0:
    docker:
      - image: docker:stable
        environment:
          DOCKER_DRIVER: overlay2
          MAJOR_VERSION: '4'
          MINOR_VERSION: '4.8'
          FULL_VERSION: '4.8.0'
          SHA256: ee95adc83852791ff6d6f9502c9d5e5afdd4e553ab4b0206aa611e7d52b44ac2
          CI_REGISTRY_IMAGE: 'containerinfra/keycloak-gatekeeper'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          docker pull $CI_REGISTRY_IMAGE:$FULL_VERSION || true

          docker build --cache-from $CI_REGISTRY_IMAGE:$FULL_VERSION --build-arg KEYCLOAK_GATEKEEPER_VERSION=${FULL_VERSION}.Final --build-arg=KEYCLOAK_GATEKEEPER_SHA256=$SHA256 -t $CI_REGISTRY_IMAGE:$FULL_VERSION --label org.opencontainers.image.revision=$CIRCLE_SHA1 .
          docker push $CI_REGISTRY_IMAGE:$FULL_VERSION

  build-v4.7.0:
    docker:
      - image: docker:stable
        environment:
          DOCKER_DRIVER: overlay2
          MAJOR_VERSION: '4'
          MINOR_VERSION: '4.7'
          FULL_VERSION: '4.7.0'
          SHA256: 2f1793e6b67a80a0cb1a253e2acc5f344e7997605a29871dfad617360940106e
          CI_REGISTRY_IMAGE: 'containerinfra/keycloak-gatekeeper'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          docker pull $CI_REGISTRY_IMAGE:$FULL_VERSION || true

          docker build --cache-from $CI_REGISTRY_IMAGE:$FULL_VERSION --build-arg KEYCLOAK_GATEKEEPER_VERSION=${FULL_VERSION}.Final --build-arg=KEYCLOAK_GATEKEEPER_SHA256=$SHA256 -t $CI_REGISTRY_IMAGE:$FULL_VERSION --label org.opencontainers.image.revision=$CIRCLE_SHA1 .
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:$MINOR_VERSION
          docker push $CI_REGISTRY_IMAGE:$FULL_VERSION
          docker push $CI_REGISTRY_IMAGE:$MINOR_VERSION

  build-pr:
    docker:
      - image: docker:stable
        environment:
          DOCKER_DRIVER: overlay2
          CI_REGISTRY_IMAGE: 'containerinfra/keycloak-gatekeeper'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker build -t $CI_REGISTRY_IMAGE:latest .

workflows:
  version: 2
  build-job:
    jobs:
      - build-v4.8.1:
          filters:
            branches:
              only: master
      - build-v4.8.0:
          filters:
            branches:
              only: master
      - build-v4.7.0:
          filters:
            branches:
              only: master
      - build-pr:
          filters:
            branches:
              ignore: master

  monthly:
    triggers:
      - schedule:
          cron: "0 0 14 * *"
          filters:
           branches:
             only:
               - master
    jobs:
      - build-v4.8.1
      - build-v4.8.0
      - build-v4.7.0

 
