version: 2
jobs:
  build-v5.0.0:
    docker:
      - image: docker:stable
        environment:
          DOCKER_DRIVER: overlay2
          MAJOR_VERSION: '5'
          MINOR_VERSION: '5.0'
          FULL_VERSION: '5.0.0'
          SHA256: 4314695d28d83652cef494549e4a068ef8c9fa285c67a3358fbe6ae4d96a3c2c
          CI_REGISTRY_IMAGE: 'containerinfra/keycloak-gatekeeper'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          docker pull $CI_REGISTRY_IMAGE:$FULL_VERSION || true

          docker build --cache-from $CI_REGISTRY_IMAGE:$FULL_VERSION --build-arg KEYCLOAK_GATEKEEPER_VERSION=${FULL_VERSION}.Final --build-arg=KEYCLOAK_GATEKEEPER_SHA256=$SHA256 -t $CI_REGISTRY_IMAGE:$FULL_VERSION --label org.opencontainers.image.revision=$CIRCLE_SHA1 .
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:$MINOR_VERSION
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:$MAJOR_VERSION
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:latest
          docker push $CI_REGISTRY_IMAGE:$FULL_VERSION
          docker push $CI_REGISTRY_IMAGE:$MINOR_VERSION
          docker push $CI_REGISTRY_IMAGE:$MAJOR_VERSION
          docker push $CI_REGISTRY_IMAGE:latest

  build-pr:
    docker:
      - image: docker:stable
        environment:
          DOCKER_DRIVER: overlay2
          CI_REGISTRY_IMAGE: 'containerinfra/keycloak-gatekeeper'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker build -t $CI_REGISTRY_IMAGE:latest .

workflows:
  version: 2
  build-job:
    jobs:
      - build-v5.0.0:
          filters:
            branches:
              only: master
      - build-pr:
          filters:
            branches:
              ignore: master

  monthly:
    triggers:
      - schedule:
          cron: "0 0 14 * *"
          filters:
           branches:
             only:
               - master
    jobs:
      - build-v5.0.0
