version: 2
jobs:
  build-v4.8.2:
    docker:
      - image: docker:stable
        environment:
          DOCKER_DRIVER: overlay2
          MAJOR_VERSION: '4'
          MINOR_VERSION: '4.8'
          FULL_VERSION: '4.8.2'
          SHA256: 399c4393a5a368ae8a963d096c6fa150918c867ca2f44f8a5c4fd49a485d23e8
          CI_REGISTRY_IMAGE: 'containerinfra/keycloak-gatekeeper'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          docker pull $CI_REGISTRY_IMAGE:$FULL_VERSION || true

          docker build --cache-from $CI_REGISTRY_IMAGE:$FULL_VERSION --build-arg KEYCLOAK_GATEKEEPER_VERSION=${FULL_VERSION}.Final --build-arg=KEYCLOAK_GATEKEEPER_SHA256=$SHA256 -t $CI_REGISTRY_IMAGE:$FULL_VERSION --label org.opencontainers.image.revision=$CIRCLE_SHA1 .
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:$MINOR_VERSION
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:$MAJOR_VERSION
          docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:latest
          docker push $CI_REGISTRY_IMAGE:$FULL_VERSION
          docker push $CI_REGISTRY_IMAGE:$MINOR_VERSION
          docker push $CI_REGISTRY_IMAGE:$MAJOR_VERSION
          docker push $CI_REGISTRY_IMAGE:latest

  build-pr:
    docker:
      - image: docker:stable
        environment:
          DOCKER_DRIVER: overlay2
          CI_REGISTRY_IMAGE: 'containerinfra/keycloak-gatekeeper'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker build -t $CI_REGISTRY_IMAGE:latest .

workflows:
  version: 2
  build-job:
    jobs:
      - build-v4.8.2:
          filters:
            branches:
              only: master
      - build-pr:
          filters:
            branches:
              ignore: master

  monthly:
    triggers:
      - schedule:
          cron: "0 0 14 * *"
          filters:
           branches:
             only:
               - master
    jobs:
      - build-v4.8.2
